-- Migration number: 0001 	 2024-06-10T13:07:05.918Z

CREATE TABLE IF NOT EXISTS dynamiclinks (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	link TEXT,
    short_link TEXT,
    clicks INTEGER,
	created_on DATE DEFAULT  CURRENT_TIMESTAMP
);